export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const GET_SHOPINGFILE = "GET_SHOPINGFILE";
export const SHOPINGFILE_LOADING = "SHOPINGFILE_LOADING";
export const SHOPING_NOT_FOUND = "SHOPING_NOT_FOUND";
export const CLEAR_CURRENT_SHOPINGFILE = "CLEAR_CURRENT_SHOPINGFILE";
export const GET_SHOPINGFILES = "GET_SHOPINGFILES";

export const DELETE_SHOPING="DELETE_SHOPING";
export const UPDATE_SHOPING="UPDATE_SHOPING";
export const ADD_SHOPINGFILE="ADD_SHOPINGFILE";

export const BUSCA_SHOPING="BUSCA_SHOPING";




export const GET_CATEGORIAFILE = "GET_CATEGORIAFILE";
export const CATEGORIAFILE_LOADING = "CATEGORIAFILE_LOADING";
export const CATEGORIA_NOT_FOUND = "CATEGORIA_NOT_FOUND";
export const CLEAR_CURRENT_CATEGORIAFILE = "CLEAR_CURRENT_CATEGORIAFILE";
export const GET_CATEGORIAFILES = "GET_CATEGORIAFILES";

export const DELETE_CATEGORIA="DELETE_CATEGORIA";
export const UPDATE_CATEGORIA="UPDATE_CATEGORIA";
export const ADD_CATEGORIAFILE="ADD_CATEGORIAFILE";

export const BUSCA_CATEGORIA="BUSCA_CATEGORIA";

export const GET_TIPOFILE = "GET_TIPOFILE";
export const TIPOFILE_LOADING = "TIPOFILE_LOADING";
export const TIPO_NOT_FOUND = "TIPO_NOT_FOUND";
export const CLEAR_CURRENT_TIPOFILE = "CLEAR_CURRENT_TIPOFILE";
export const GET_TIPOFILES = "GET_TIPOFILES";

export const DELETE_TIPO="DELETE_TIPO";
export const UPDATE_TIPO="UPDATE_TIPO";
export const ADD_TIPOFILE="ADD_TIPOFILE";



export const GET_SERIEFILE = "GET_SERIEFILE";
export const SERIEFILE_LOADING = "SERIEFILE_LOADING";
export const SERIE_NOT_FOUND = "SERIE_NOT_FOUND";
export const CLEAR_CURRENT_SERIEFILE = "CLEAR_CURRENT_SERIEFILE";
export const GET_SERIEFILES = "GET_SERIEFILES";

export const DELETE_SERIE="DELETE_SERIE";
export const UPDATE_SERIE="UPDATE_SERIE";
export const ADD_SERIEFILE="ADD_SERIEFILE";



export const GET_UMEDIDAFILE = "GET_UMEDIDAFILE";
export const UMEDIDAFILE_LOADING = "UMEDIDAFILE_LOADING";
export const UMEDIDA_NOT_FOUND = "UMEDIDA_NOT_FOUND";
export const CLEAR_CURRENT_UMEDIDAFILE = "CLEAR_CURRENT_UMEDIDAFILE";
export const GET_UMEDIDAFILES = "GET_UMEDIDAFILES";

export const DELETE_UMEDIDA="DELETE_UMEDIDA";
export const UPDATE_UMEDIDA="UPDATE_UMEDIDA";
export const ADD_UMEDIDAFILE="ADD_UMEDIDAFILE";



export const GET_LINEAFILE = "GET_LINEAFILE";
export const LINEAFILE_LOADING = "LINEAFILE_LOADING";
export const LINEA_NOT_FOUND = "LINEA_NOT_FOUND";
export const CLEAR_CURRENT_LINEAFILE = "CLEAR_CURRENT_LINEAFILE";
export const GET_LINEAFILES = "GET_LINEAFILES";

export const DELETE_LINEA="DELETE_LINEA";
export const UPDATE_LINEA="UPDATE_LINEA";
export const ADD_LINEAFILE="ADD_LINEAFILE";



export const GET_ALMACENFILE = "GET_ALMACENFILE";
export const ALMACENFILE_LOADING = "ALMACENFILE_LOADING";
export const ALMACEN_NOT_FOUND = "ALMACEN_NOT_FOUND";
export const CLEAR_CURRENT_ALMACENFILE = "CLEAR_CURRENT_ALMACENFILE";
export const GET_ALMACENFILES = "GET_ALMACENFILES";

export const DELETE_ALMACEN="DELETE_ALMACEN";
export const UPDATE_ALMACEN="UPDATE_ALMACEN";
export const ADD_ALMACENFILE="ADD_ALMACENFILE";



export const GET_CLIENTEFILE = "GET_CLIENTEFILE";
export const CLIENTEFILE_LOADING = "CLIENTEFILE_LOADING";
export const CLIENTE_NOT_FOUND = "CLIENTE_NOT_FOUND";
export const CLEAR_CURRENT_CLIENTEFILE = "CLEAR_CURRENT_CLIENTEFILE";
export const GET_CLIENTEFILES = "GET_CLIENTEFILES";

export const DELETE_CLIENTE="DELETE_CLIENTE";
export const UPDATE_CLIENTE="UPDATE_CLIENTE";
export const ADD_CLIENTEFILE="ADD_CLIENTEFILE";


export const GET_ARTICULOFILE = "GET_ARTICULOFILE";
export const ARTICULOFILE_LOADING = "ARTICULOFILE_LOADING";
export const ARTICULO_NOT_FOUND = "CLIENTE_NOT_FOUND";
export const CLEAR_CURRENT_ARTICULOFILE = "CLEAR_CURRENT_ARTICULOFILE";
export const GET_ARTICULOFILES = "GET_ARTICULOFILES";

export const DELETE_ARTICULO="DELETE_ARTICULO";
export const UPDATE_ARTICULO="UPDATE_ARTICULO";
export const ADD_ARTICULOFILE="ADD_ARTICULOFILE";






export const GET_PRODUCTOFILE = "GET_PRODUCTOFILE";
export const PRODUCTOFILE_LOADING = "PRODUCTOFILE_LOADING";
export const PRODUCTO_NOT_FOUND = "PRODUCTO_NOT_FOUND";
export const CLEAR_CURRENT_PRODUCTOFILE = "CLEAR_CURRENT_PRODUCTOFILE";
export const GET_PRODUCTOFILES = "GET_PRODUCTOFILES";

export const DELETE_PRODUCTO="DELETE_PRODUCTO";
export const UPDATE_PRODUCTO="UPDATE_PRODUCTO";
export const ADD_PRODUCTOFILE="ADD_PRODUCTOFILE";

export const BUSCA_PRO="BUSCA_PRO";

export const GET_CARTPRO = "GET_CARTPRO";
export const GET_CARTCATE = "GET_CARTCATE";
export const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
 
export const SHOW_CART_DLG = "SHOW_CART_DLG";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const DELETE_CART = "DELETE_CART";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";

export const UPDATE_CART_ITEM_DESCRIPCION = "UPDATE_CART_ITEM_DESCRIPCION";
export const SET_CHECKEDOUT_ITEMS = "SET_CHECKEDOUT_ITEMS";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const LOGOUT = "LOGOUT";
export const VENTAFILE_LOADING="VENTAFILE_LOADING";
export const CLEAR_CURRENT_VENTAFILE="CLEAR_CURRENT_VENTAFILE";

export const UPDATE_CART_ITEM_PRICE="UPDATE_CART_ITEM_PRICE";
export const UPDATE_CART_ITEM_TOTAL="UPDATE_CART_ITEM_TOTAL";


export const GET_CARTSUNAT="GET_CARTSUNAT";
export const SUNATFILE_LOADING="SUNATFILE_LOADING";
export const CLEAR_CURRENT_SUNATFILE="CLEAR_CURRENT_SUNATFILE";
    

export const GET_CARTDNI="GET_CARTDNI";
export const DNIFILE_LOADING="DNIFILE_LOADING";
export const CLEAR_CURRENT_DNIFILE="CLEAR_CURRENT_DNIFILE";


export const GET_CARTNDOCU = "GET_CARTNDOCU";
export const NDOCUFILE_LOADING = "NDOCUFILE_LOADING";
export const CLEAR_CURRENT_NDOCUFILE = "CLEAR_CURRENT_NDOCUFILE";


export const GET_CARTVENTASERIE = "GET_CARTVENTASERIE";
export const VENTASERIEFILE_LOADING="VENTASERIEFILE_LOADING";
export const CLEAR_CURRENT_VENTASERIEFILE="CLEAR_CURRENT_VENTASERIEFILE";

//
export const ADD_TITULO = 'ADD_TITULO';
export const SHOW_TITULO = 'SHOW_TITULO';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SHOW_MENU = 'SHOW_MENU';

